//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Lab3.MovieServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MovieServiceReference.IMovieService")]
    public interface IMovieService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieService/GetAllMovies", ReplyAction="http://tempuri.org/IMovieService/GetAllMoviesResponse")]
        System.Xml.Linq.XElement GetAllMovies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieService/GetAllMovies", ReplyAction="http://tempuri.org/IMovieService/GetAllMoviesResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetAllMoviesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieService/GetTopTenMovies", ReplyAction="http://tempuri.org/IMovieService/GetTopTenMoviesResponse")]
        System.Xml.Linq.XElement GetTopTenMovies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieService/GetTopTenMovies", ReplyAction="http://tempuri.org/IMovieService/GetTopTenMoviesResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetTopTenMoviesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMovieServiceChannel : MVC_Lab3.MovieServiceReference.IMovieService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovieServiceClient : System.ServiceModel.ClientBase<MVC_Lab3.MovieServiceReference.IMovieService>, MVC_Lab3.MovieServiceReference.IMovieService {
        
        public MovieServiceClient() {
        }
        
        public MovieServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovieServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.Linq.XElement GetAllMovies() {
            return base.Channel.GetAllMovies();
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetAllMoviesAsync() {
            return base.Channel.GetAllMoviesAsync();
        }
        
        public System.Xml.Linq.XElement GetTopTenMovies() {
            return base.Channel.GetTopTenMovies();
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetTopTenMoviesAsync() {
            return base.Channel.GetTopTenMoviesAsync();
        }
    }
}
